#!/usr/bin/env bash
# ffprobe stream inventory — run after baseline scan to get codec/resolution metadata
# Usage: sudo ./04_ffprobe_inventory.sh [interface]

set -euo pipefail

IFACE="${1:-$(ip route | awk '/default/{print $5; exit}')}"
BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REPORT_DIR="$BASE_DIR/reports"
LOG_DIR="$BASE_DIR/logs"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
INVENTORY="$REPORT_DIR/stream_inventory_${TIMESTAMP}.md"
JSON_LOG="$LOG_DIR/ffprobe_${TIMESTAMP}.json"
SNAPSHOT="$LOG_DIR/metrics_snapshot.json"

mkdir -p "$REPORT_DIR" "$LOG_DIR"

GRN='\033[0;32m'; YLW='\033[1;33m'; RED='\033[0;31m'; BLD='\033[1m'; NC='\033[0m'
ok()  { echo -e "${GRN}✓${NC} $*"; }
warn(){ echo -e "${YLW}⚠${NC} $*"; }
hdr() { echo -e "\n${BLD}=== $* ===${NC}"; }

command -v ffprobe &>/dev/null || { echo "ERROR: ffprobe not installed"; exit 1; }

hdr "IPTV Stream Inventory via ffprobe"

# Discover active streams from exporter snapshot or tcpdump
STREAMS=()
if [[ -f "$SNAPSHOT" ]]; then
    mapfile -t STREAMS < <(python3 -c "
import json
d = json.load(open('$SNAPSHOT'))
for s in d.get('streams', []):
    print(s['group'] + ':' + str(s['port']))
")
    ok "Found ${#STREAMS[@]} active streams from exporter snapshot"
else
    warn "No exporter snapshot found — scanning with tcpdump (30s)..."
    mapfile -t STREAMS < <(
        sudo timeout 30 tcpdump -i "$IFACE" -n 'dst net 239.0.0.0/8' 2>/dev/null \
        | awk '{print $5}' | sed 's/\.$/:/' | sort -u | head -20
    )
fi

if [[ ${#STREAMS[@]} -eq 0 ]]; then
    warn "No active streams found. Are TVs on?"
    exit 0
fi

echo ""
echo -e "${BLD}Probing ${#STREAMS[@]} streams (10s each)...${NC}"
echo ""

declare -A RESULTS
ALL_JSON="[]"

for STREAM in "${STREAMS[@]}"; do
    GROUP="${STREAM%%:*}"
    PORT="${STREAM##*:}"
    URL="udp://@${GROUP}:${PORT}?fifo_size=1000000&overrun_nonfatal=1"

    echo -n "  Probing $GROUP:$PORT ... "

    RAW=$(timeout 12 ffprobe \
        -v quiet \
        -print_format json \
        -show_streams \
        -show_format \
        "$URL" 2>/dev/null || echo "{}")

    if echo "$RAW" | python3 -c "import json,sys; d=json.load(sys.stdin); exit(0 if d.get('streams') else 1)" 2>/dev/null; then
        INFO=$(echo "$RAW" | python3 -c "
import json, sys
d = json.load(sys.stdin)
streams = d.get('streams', [])
fmt = d.get('format', {})
video = next((s for s in streams if s.get('codec_type') == 'video'), {})
audio = [s for s in streams if s.get('codec_type') == 'audio']
print('|'.join([
    video.get('codec_name', 'unknown'),
    video.get('width','?') and str(video.get('width','?')) + 'x' + str(video.get('height','?')) or 'unknown',
    video.get('r_frame_rate','?').split('/')[0] if '/' in str(video.get('r_frame_rate','')) else str(video.get('r_frame_rate','?')),
    str(round(int(fmt.get('bit_rate', 0)) / 1000)) + ' kbps' if fmt.get('bit_rate') else 'unknown',
    str(len(audio)) + ' track(s)',
    ', '.join(set(a.get('codec_name','?') for a in audio)) or 'none',
]))
")
        CODEC=$(echo "$INFO" | cut -d'|' -f1)
        RES=$(echo "$INFO"   | cut -d'|' -f2)
        FPS=$(echo "$INFO"   | cut -d'|' -f3)
        BPS=$(echo "$INFO"   | cut -d'|' -f4)
        ATRACKS=$(echo "$INFO" | cut -d'|' -f5)
        ACODEC=$(echo "$INFO"  | cut -d'|' -f6)
        ok "${CODEC} ${RES} @ ${FPS}fps | ${BPS} | audio: ${ATRACKS} (${ACODEC})"
        RESULTS[$STREAM]="$CODEC|$RES|$FPS|$BPS|$ATRACKS|$ACODEC|decodable"
    else
        warn "no decode (IGMP join failed, scrambled, or not RTP)"
        RESULTS[$STREAM]="?|?|?|?|?|?|failed"
    fi
done

# Write markdown inventory
cat > "$INVENTORY" <<MARKDOWN
# Stream Inventory — ffprobe Results

**Date:** $(date)
**Interface:** $IFACE
**Streams probed:** ${#STREAMS[@]}

| Stream | Video Codec | Resolution | FPS | Bitrate | Audio | Status |
|--------|------------|------------|-----|---------|-------|--------|
MARKDOWN

for STREAM in "${!RESULTS[@]}"; do
    IFS='|' read -r CODEC RES FPS BPS ATRACKS ACODEC STATUS <<< "${RESULTS[$STREAM]}"
    echo "| $STREAM | $CODEC | $RES | $FPS | $BPS | $ATRACKS $ACODEC | $STATUS |" >> "$INVENTORY"
done

echo "" >> "$INVENTORY"
echo "*Generated by hotel-iptv/scripts/04_ffprobe_inventory.sh — $(date)*" >> "$INVENTORY"

hdr "Inventory complete"
ok "Report: $INVENTORY"
echo ""
cat "$INVENTORY"
